# A sample Gemfile
source "https://rubygems.org"

gem 'rubocop'
gem 'ruby-debug-ide'
gem 'debase'
gem 'rcodetools'
gem 'fastri'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'rake'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'bcrypt'

gem 'cloudinary'
gem 'dotenv'
gem 'json'

group :development do
  gem 'sqlite3','~>1.3.13'
end

group :production do
  gem 'pg' , '~>0.18'
end

gem 'pry'

gem 'googleauth'
gem 'google-api-client', '0.9'